### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by huckbit** [huckbit/stockApp#5]
**Fatal error:** Class 'Huckbit\StockApp\Db' not found in **../dependencies.php on line 26**

Something missing here on line 26???

    `$db = new \Huckbit\StockApp\Db($settings[ '...' ]);`

Thanks!!!

**Comment by palicao** [comment]
have you tried to re-run composer install before?

**Comment by huckbit** [comment]
No I didn't know that 👍 thanks mate!!!
